/**
 * Full chapter body text for the flagship e-book, one entry per language
 * code in FLAGSHIP_TRANSLATIONS (prisma/content/flagship-book.ts). Six
 * chapters per language, matching each translation's tableOfContents
 * order. Original AXTO.dev editorial writing — used both to render the
 * sellable PDF (scripts/generate-flagship-pdfs.ts) and to keep the book
 * detail page's description in sync with what's actually inside the file.
 */

export interface FlagshipChapters {
  languageCode: string;
  chapters: string[]; // plain text, paragraphs separated by \n\n
}

export const FLAGSHIP_CHAPTERS: FlagshipChapters[] = [
  {
    languageCode: "en",
    chapters: [
      "Most jobs, for most of history, didn't reward sustained concentration. Output was tied to hours at a bench or a desk, not to the quality of thinking inside those hours. That has quietly reversed. In knowledge work, two people with the same tools and the same time can produce wildly different results, and the difference is almost always the ability to hold a single hard problem in mind without letting it fragment.\n\nThat ability is now scarce, and scarce things are valuable. The average knowledge worker is interrupted every few minutes by a notification, a message, or their own habit of checking something. Each of those interruptions is small on its own, which is exactly why they're dangerous — no single one feels like a decision to abandon focus, so nobody ever consciously chooses to. Treating focus as a skill you train, rather than a trait you either have or don't, is the first shift this book asks you to make.",
      "Context-switching feels efficient. It isn't. Every time you move from one task to another — even a small one, like glancing at a chat notification — your brain doesn't cleanly close the first task and open the second. Part of your attention stays behind, still processing the thing you left unfinished, in a phenomenon researchers call attention residue. The result is that the second task gets less of you than it would have if you'd finished the first one properly.\n\nThe cost compounds. A single interruption of a few seconds can cost fifteen to twenty-five minutes of true focused recovery time, because you're not just resuming a task — you're reconstructing the mental model you had built before the interruption. Multiply that by the dozens of small interruptions in an average day, and most people are never more than a few minutes away from working at partial capacity. Recognizing this cost is what makes protecting focus feel less like a luxury and more like basic economics.",
      "Willpower is an unreliable way to start deep work, because it depends on a mental state that's already depleted by the time you need it most. A ritual works better: a short, fixed sequence of actions that you repeat identically every time, until your brain learns to associate the sequence itself with the shift into focused work — the same way a runner's warm-up signals the body to prepare, independent of how motivated the runner feels that day.\n\nA workable three-step ritual: first, close everything unrelated to the task and write the single outcome you're aiming for in one sentence, at the top of a blank page or document. Second, set a visible timer for a fixed block — twenty-five to fifty minutes is a reasonable range to start with. Third, take one deliberate breath and start the smallest possible piece of the task, not the whole thing. The specific steps matter less than the repetition; consistency is what turns the ritual into a trigger.",
      "Environment design means changing your surroundings so that focus is the default, rather than something you have to fight for using willpower after the distraction is already in front of you. This is more reliable than self-discipline because it removes the decision entirely — a notification you've already silenced can't tempt you, no matter how tired or unmotivated you feel.\n\nA short list of changes covers most of the ground: turn off non-essential notifications at the system level rather than trying to ignore them individually; keep your phone in another room during focus blocks rather than face-down on the desk, since visibility alone measurably reduces available attention; and prepare your workspace the night before, so the first ten minutes of a focus session aren't spent finding files or deciding what to work on. None of these changes require new software or a system overhaul — they require making a small number of decisions once, so you don't have to make them daily.",
      "Protecting focus time from other people is usually the hardest part, because saying no can feel like it damages a relationship or signals that you're not a team player. The solution isn't to become less available — it's to be available on a predictable schedule instead of constantly, and to communicate that schedule clearly so other people can plan around it rather than being surprised by it.\n\nA few scripts help: \"I'm heads-down until 2pm — can I get back to you right after?\" gives a concrete time rather than an open-ended no. \"Let's put this on the agenda for our next sync\" converts an interruption into a scheduled conversation. For genuinely urgent matters, agree in advance on what counts as urgent enough to interrupt a focus block, so the exception stays rare instead of becoming the rule that quietly erodes the whole system.",
      "Habits fade without a feedback loop, and a good first week of focused work is easy to lose in a mediocre second week if nothing is tracked. A weekly review closes that loop: once a week, spend ten minutes answering three questions — how many focus blocks did I actually complete, what interrupted me most often, and what's one adjustment for next week.\n\nThe review works because it turns focus from a vague intention into a measured practice, the same way tracking weight or spending changes behavior simply by making it visible. Keep the review short and consistent rather than elaborate and occasional; a ten-minute habit you do every week beats a thorough audit you do once and never repeat. Over a few months, this single habit is usually what separates people who read a productivity guide once from people who actually change how they work.",
    ],
  },
  {
    languageCode: "en-CA",
    chapters: [
      "Most jobs, for most of history, didn't reward sustained concentration. Output was tied to hours at a bench or a desk, not to the quality of thinking inside those hours. That has quietly reversed. In knowledge work, two people with the same tools and the same time can produce wildly different results, and the difference is almost always the ability to hold a single hard problem in mind without letting it fragment.\n\nThat ability is now scarce, and scarce things are valuable. The average knowledge worker is interrupted every few minutes by a notification, a message, or their own habit of checking something. Each of those interruptions is small on its own, which is exactly why they're dangerous — no single one feels like a decision to abandon focus, so nobody ever consciously chooses to. Treating focus as a skill you train, rather than a trait you either have or don't, is the first shift this book asks you to make.",
      "Context-switching feels efficient. It isn't. Every time you move from one task to another — even a small one, like glancing at a chat notification — your brain doesn't cleanly close the first task and open the second. Part of your attention stays behind, still processing the thing you left unfinished, in a phenomenon researchers call attention residue. The result is that the second task gets less of you than it would have if you'd finished the first one properly.\n\nThe cost compounds. A single interruption of a few seconds can cost fifteen to twenty-five minutes of true focused recovery time, because you're not just resuming a task — you're reconstructing the mental model you had built before the interruption. Multiply that by the dozens of small interruptions in an average day, and most people are never more than a few minutes away from working at partial capacity. Recognizing this cost is what makes protecting focus feel less like a luxury and more like basic economics.",
      "Willpower is an unreliable way to start deep work, because it depends on a mental state that's already depleted by the time you need it most. A ritual works better: a short, fixed sequence of actions you repeat identically every time, until your brain learns to associate the sequence itself with the shift into focused work — the same way a runner's warm-up signals the body to prepare, independent of how motivated the runner feels that day.\n\nA workable three-step ritual: first, close everything unrelated to the task and write the single outcome you're aiming for in one sentence, at the top of a blank page or document. Second, set a visible timer for a fixed block — twenty-five to fifty minutes is a reasonable range to start with. Third, take one deliberate breath and start the smallest possible piece of the task, not the whole thing. The specific steps matter less than the repetition; consistency is what turns the ritual into a trigger.",
      "Environment design means changing your surroundings so that focus is the default, rather than something you have to fight for using willpower after the distraction is already in front of you. This is more reliable than self-discipline because it removes the decision entirely — a notification you've already silenced can't tempt you, no matter how tired or unmotivated you feel.\n\nA short list of changes covers most of the ground: turn off non-essential notifications at the system level rather than trying to ignore them individually; keep your phone in another room during focus blocks rather than face-down on the desk, since visibility alone measurably reduces available attention; and prepare your workspace the night before, so the first ten minutes of a focus session aren't spent finding files or deciding what to work on. None of these changes require new software or a system overhaul — they require making a small number of decisions once, so you don't have to make them daily.",
      "Protecting focus time from other people is usually the hardest part, because saying no can feel like it damages a relationship or signals that you're not a team player. The solution isn't to become less available — it's to be available on a predictable schedule instead of constantly, and to communicate that schedule clearly so colleagues can plan around it rather than being surprised by it.\n\nA few scripts help: \"I'm heads-down until 2pm — can I get back to you right after?\" gives a concrete time rather than an open-ended no. \"Let's put this on the agenda for our next sync\" converts an interruption into a scheduled conversation. For genuinely urgent matters, agree in advance on what counts as urgent enough to interrupt a focus block, so the exception stays rare instead of becoming the rule that quietly erodes the whole system.",
      "Habits fade without a feedback loop, and a good first week of focused work is easy to lose in a mediocre second week if nothing is tracked. A weekly review closes that loop: once a week, spend ten minutes answering three questions — how many focus blocks did I actually complete, what interrupted me most often, and what's one adjustment for next week.\n\nThe review works because it turns focus from a vague intention into a measured practice, the same way tracking weight or spending changes behaviour simply by making it visible. Keep the review short and consistent rather than elaborate and occasional; a ten-minute habit you do every week beats a thorough audit you do once and never repeat. Over a few months, this single habit is usually what separates people who read a productivity guide once from people who actually change how they work.",
    ],
  },
  {
    languageCode: "id",
    chapters: [
      "Sepanjang sejarah, kebanyakan pekerjaan tidak menghargai konsentrasi yang berkelanjutan. Hasil kerja diukur dari jam yang dihabiskan di meja kerja, bukan dari kualitas pemikiran selama jam-jam itu. Keadaan itu kini berbalik secara diam-diam. Dalam pekerjaan berbasis pengetahuan, dua orang dengan alat dan waktu yang sama bisa menghasilkan hasil yang sangat berbeda, dan perbedaannya hampir selalu terletak pada kemampuan menahan satu masalah sulit dalam pikiran tanpa membiarkannya pecah.\n\nKemampuan itu kini langka, dan yang langka itu berharga. Rata-rata pekerja pengetahuan terganggu setiap beberapa menit oleh notifikasi, pesan, atau kebiasaannya sendiri untuk memeriksa sesuatu. Setiap gangguan itu kecil jika berdiri sendiri — dan justru itulah yang membuatnya berbahaya, karena tidak ada satu pun yang terasa seperti keputusan untuk meninggalkan fokus, sehingga tidak ada yang pernah secara sadar memilihnya. Memperlakukan fokus sebagai keterampilan yang dilatih, bukan sifat bawaan yang dimiliki atau tidak, adalah pergeseran pertama yang diminta buku ini.",
      "Berpindah-pindah tugas terasa efisien. Padahal tidak. Setiap kali kamu berpindah dari satu tugas ke tugas lain — bahkan yang kecil, seperti melirik notifikasi chat — otakmu tidak menutup tugas pertama dengan bersih sebelum membuka tugas kedua. Sebagian perhatianmu tertinggal, masih memproses hal yang belum selesai, dalam fenomena yang oleh peneliti disebut sisa perhatian (attention residue). Akibatnya, tugas kedua mendapatkan dirimu yang lebih sedikit dibanding jika kamu menyelesaikan tugas pertama dengan tuntas.\n\nBiayanya menumpuk. Satu gangguan yang hanya berlangsung beberapa detik bisa menghabiskan lima belas hingga dua puluh lima menit waktu pemulihan fokus sungguhan, karena kamu tidak sekadar melanjutkan tugas — kamu membangun kembali model mental yang sudah kamu susun sebelum gangguan itu. Kalikan dengan puluhan gangguan kecil dalam sehari yang biasa, dan kebanyakan orang tidak pernah lebih dari beberapa menit dari bekerja dalam kapasitas yang tidak penuh. Menyadari biaya ini membuat melindungi fokus terasa bukan kemewahan, melainkan hitungan ekonomi dasar.",
      "Kemauan (willpower) adalah cara yang tidak andal untuk memulai kerja mendalam, karena ia bergantung pada kondisi mental yang justru sudah terkuras saat paling dibutuhkan. Ritual bekerja lebih baik: urutan tindakan pendek dan tetap yang kamu ulangi persis sama setiap kali, sampai otakmu belajar mengasosiasikan urutan itu sendiri dengan peralihan menuju kerja fokus — sama seperti pemanasan pelari yang memberi sinyal pada tubuh untuk bersiap, terlepas dari seberapa termotivasi pelari itu hari itu.\n\nRitual tiga langkah yang bisa dicoba: pertama, tutup semua yang tidak berkaitan dengan tugas dan tuliskan satu hasil yang kamu tuju dalam satu kalimat, di bagian atas halaman atau dokumen kosong. Kedua, pasang pengatur waktu yang terlihat untuk satu blok waktu tetap — dua puluh lima hingga lima puluh menit adalah rentang awal yang wajar. Ketiga, tarik satu napas dengan sengaja dan mulai dari bagian terkecil dari tugas, bukan keseluruhannya. Langkah spesifiknya kurang penting dibanding pengulangannya; konsistensi itulah yang mengubah ritual menjadi pemicu.",
      "Desain lingkungan berarti mengubah sekelilingmu sehingga fokus menjadi kondisi bawaan, bukan sesuatu yang harus kamu perjuangkan dengan kemauan setelah gangguan sudah ada di depan mata. Cara ini lebih andal dibanding disiplin diri karena ia menghilangkan keputusan itu sepenuhnya — notifikasi yang sudah kamu matikan tidak bisa menggodamu, seberapa pun lelah atau tidak termotivasinya kamu.\n\nDaftar singkat perubahan ini mencakup sebagian besar yang diperlukan: matikan notifikasi yang tidak penting di tingkat sistem, bukan mencoba mengabaikannya satu per satu; simpan ponsel di ruangan lain selama blok fokus, bukan sekadar menelungkupkannya di meja, karena keterlihatan saja sudah terbukti mengurangi perhatian yang tersedia; dan siapkan ruang kerjamu pada malam sebelumnya, agar sepuluh menit pertama sesi fokus tidak habis untuk mencari berkas atau memutuskan apa yang dikerjakan. Tidak satu pun dari perubahan ini membutuhkan aplikasi baru atau perombakan sistem — cukup membuat beberapa keputusan sekali saja, agar tidak perlu membuatnya setiap hari.",
      "Melindungi waktu fokus dari orang lain biasanya menjadi bagian tersulit, karena menolak bisa terasa seperti merusak hubungan atau memberi kesan kamu bukan pemain tim. Solusinya bukan menjadi kurang tersedia — melainkan tersedia dengan jadwal yang bisa diprediksi, bukan terus-menerus, dan mengomunikasikan jadwal itu dengan jelas agar orang lain bisa merencanakan sekitarnya, bukan dikejutkan olehnya.\n\nBeberapa contoh kalimat yang membantu: \"Saya sedang fokus sampai jam 2 siang — boleh saya balas segera setelah itu?\" memberikan waktu yang konkret, bukan penolakan tanpa batas. \"Mari kita masukkan ini ke agenda pertemuan berikutnya\" mengubah gangguan menjadi percakapan terjadwal. Untuk hal yang benar-benar mendesak, sepakati sejak awal apa yang dianggap cukup mendesak untuk menyela blok fokus, agar pengecualian tetap jarang dan tidak diam-diam menjadi aturan yang mengikis seluruh sistem.",
      "Kebiasaan memudar tanpa umpan balik, dan minggu pertama kerja fokus yang bagus mudah hilang di minggu kedua yang biasa-biasa saja jika tidak ada yang dipantau. Tinjauan mingguan menutup celah itu: sekali seminggu, luangkan sepuluh menit untuk menjawab tiga pertanyaan — berapa blok fokus yang benar-benar kuselesaikan, apa yang paling sering mengganggu, dan apa satu penyesuaian untuk minggu depan.\n\nTinjauan ini berhasil karena mengubah fokus dari niat samar menjadi praktik yang terukur, sama seperti mencatat berat badan atau pengeluaran mengubah perilaku hanya dengan membuatnya terlihat. Buat tinjauan tetap singkat dan konsisten, bukan rumit dan sesekali; kebiasaan sepuluh menit yang dilakukan setiap minggu mengalahkan audit menyeluruh yang dilakukan sekali lalu tidak pernah diulang. Dalam beberapa bulan, kebiasaan tunggal ini biasanya yang membedakan orang yang hanya membaca panduan produktivitas sekali dengan orang yang benar-benar mengubah cara kerjanya.",
    ],
  },
  {
    languageCode: "zh",
    chapters: [
      "在历史上的大多数时期，大部分工作并不奖励持续的专注力。产出取决于在工位上度过的时长，而不是那些时间里思考的质量。这种情况已悄然逆转。在知识型工作中，拥有相同工具和相同时间的两个人，产出可能天差地别，而差异几乎总是取决于一个人能否将一个困难的问题稳稳地留在脑海中，而不让它被打散。\n\n这种能力如今很稀有，而稀有的东西是珍贵的。普通知识工作者平均每隔几分钟就会被通知、消息，或者自己查看某物的习惯打断一次。每一次打断单独看都很小——这正是它危险的原因，因为没有哪一次感觉像是一个放弃专注的决定，所以没有人会真正有意识地做出这个选择。把专注当作一种可以训练的技能，而不是一种天生有或没有的特质，是本书要求你做出的第一个转变。",
      "任务切换看起来很高效，但实际上并非如此。每次你从一项任务转向另一项——哪怕只是瞥一眼聊天通知这样的小事——你的大脑并不会干净利落地关闭第一项任务再打开第二项。你的一部分注意力会留在原地，继续处理那件未完成的事情，研究者将这种现象称为“注意力残留”。结果是，第二项任务得到的你，比你完整做完第一项任务后再开始时要少。\n\n这种代价会不断累积。一次只持续几秒钟的打断，可能需要十五到二十五分钟才能真正恢复专注，因为你不只是在继续一项任务，而是在重建打断发生前你已经搭建好的思维模型。把这乘以普通一天里那几十次小小的打断，大多数人几乎从未真正处于满负荷工作状态，随时可能只差几分钟就滑回半专注状态。认清这种代价，会让保护专注力不再像是一种奢侈，而更像是基本的经济账。",
      "依靠意志力来开始深度工作并不可靠，因为意志力恰恰在你最需要它的时候已经被消耗殆尽。仪式化的做法效果更好：一套简短、固定的动作序列，每次都完全相同地重复，直到大脑学会将这个序列本身与进入专注状态联系起来——就像跑步者的热身动作会向身体发出准备信号，而与那天跑步者的动力高低无关。\n\n一套可行的三步仪式：第一，关闭与任务无关的一切，把你要达成的唯一目标用一句话写在空白页或文档的最上方。第二，为固定的一段时间设置一个看得见的计时器——二十五到五十分钟是一个合理的起始范围。第三，有意识地深吸一口气，从任务中最小的一部分开始，而不是整个任务。具体步骤是什么并不重要，重要的是重复；正是这种一致性，把仪式变成了一个触发信号。",
      "环境设计意味着改变你周围的环境，使专注成为默认状态，而不是等干扰已经出现在眼前时，还要靠意志力去对抗它。这比自律更可靠，因为它彻底移除了那个决定——一个你已经关闭的通知，无论你有多疲惫、多缺乏动力，都无法诱惑你。\n\n一份简短的清单就能覆盖大部分要点：在系统层面关闭非必要通知，而不是逐一去忽略它们；专注时段把手机放在另一个房间，而不只是扣在桌面上，因为仅仅是手机可见这一点，就已被证明会显著削弱可用的注意力；提前一晚整理好工作空间，这样专注时段的前十分钟就不会浪费在找文件或决定要做什么上。这些改变都不需要新软件或彻底的系统改造——只需要一次性做出少量决定，之后就不必每天重新做决定。",
      "保护专注时间不受他人打扰，通常是最难的部分，因为拒绝别人会让人感觉像是在破坏关系，或显得自己不够团队合作。解决办法不是变得更难联系到，而是按可预测的日程安排来可被联系到，而不是随时都能被找到，并且把这个日程清楚地传达出去，让别人能围绕它做计划，而不是被它打个措手不及。\n\n几个实用的说法：“我在下午两点前需要专心处理，之后马上回复你可以吗？”给出的是一个具体的时间，而不是无限期的拒绝。“我们把这个放到下次同步会议的议程里吧”把一次打断变成了一次有安排的对话。对于真正紧急的事情，提前约定好什么程度才算足够紧急、值得打断专注时段，这样例外情况才能保持稀少，而不会在不知不觉中变成侵蚀整个系统的常态。",
      "习惯如果没有反馈循环就会逐渐消退，一个专注工作的良好开局，如果没有任何追踪，很容易在平平无奇的第二周就被消耗殆尽。每周回顾能补上这个缺口：每周花十分钟回答三个问题——我实际完成了多少个专注时段、最常打断我的是什么、下周要做的一个调整是什么。\n\n这种回顾之所以有效，是因为它把专注从一个模糊的意愿，变成了一种可衡量的习惯，就像记录体重或支出，仅仅因为让它变得可见，就能改变行为。让回顾保持简短和持续，而不是繁琐且偶尔为之；每周十分钟的习惯，胜过做一次之后再也不重复的详尽审查。几个月之后，正是这一个习惯，通常区分出那些只读过一次生产力指南的人，和那些真正改变了工作方式的人。",
    ],
  },
  {
    languageCode: "ja",
    chapters: [
      "歴史の大部分において、たいていの仕事は持続的な集中力に報酬を与えてはこなかった。成果はデスクで過ごした時間の長さに結びついており、その時間内の思考の質には結びついていなかった。その状況は、静かに逆転している。知識労働においては、同じ道具と同じ時間を持つ二人がまったく異なる成果を生み出すことがあり、その違いはほぼ常に、一つの難しい問題を頭の中で崩壊させずに保持できるかどうかにかかっている。\n\nその能力は今や希少であり、希少なものには価値がある。平均的な知識労働者は、通知やメッセージ、あるいは何かを確認するという自分自身の習慣によって、数分ごとに中断されている。それぞれの中断は単独では小さい——だからこそ危険なのだ。どの中断も「集中をあきらめる決断」だとは感じられないため、誰も意識的にそれを選んではいない。集中力を、生まれつき持っているかどうかの資質としてではなく、訓練できるスキルとして扱うことが、本書が求める最初の転換である。",
      "タスクの切り替えは効率的に感じられる。しかし実際はそうではない。あるタスクから別のタスクへ移るたびに——チャットの通知をちらりと見るような小さなことであっても——脳は最初のタスクをきれいに閉じてから二つ目を開くわけではない。注意の一部はそこに残り、終えられなかったことをまだ処理し続けている。研究者たちはこれを「注意の残留（attention residue）」と呼ぶ。結果として、二つ目のタスクは、最初のタスクをきちんと終えてから取り組んだ場合よりも、少ない集中力しか受け取れない。\n\nそのコストは積み重なる。わずか数秒の中断であっても、真に集中した状態を取り戻すには十五分から二十五分かかることがある。単にタスクを再開するのではなく、中断前に築いていた思考の枠組みを再構築しなければならないからだ。平均的な一日に起こる何十もの小さな中断にこれを掛け合わせれば、ほとんどの人は常に部分的な集中力でしか働けていないことになる。このコストを認識することで、集中力を守ることは贅沢ではなく、基本的な経済合理性の問題だと感じられるようになる。",
      "意志力は深い仕事を始める手段としては信頼できない。なぜなら、それが最も必要な瞬間には、すでに使い果たされている精神状態に依存しているからだ。儀式（ルーティン）の方がうまく機能する。短く固定された一連の動作を毎回まったく同じように繰り返すことで、脳がその手順自体を集中状態への移行と結びつけて学習していく——ランナーのウォームアップが、その日のやる気にかかわらず、体に準備を促す合図となるのと同じ仕組みだ。\n\n実践しやすい三段階の儀式はこうだ。第一に、タスクに関係のないものをすべて閉じ、目指す唯一の成果を一文で空白のページやドキュメントの一番上に書く。第二に、固定された時間ブロックのために目に見えるタイマーを設定する——最初は二十五分から五十分程度が妥当な範囲だ。第三に、意識的に一呼吸してから、タスク全体ではなく、その中で最も小さな部分から始める。具体的な手順の内容よりも、繰り返すこと自体が重要であり、その一貫性こそが儀式を「引き金」に変える。",
      "環境デザインとは、周囲の環境を変えることで、集中がデフォルトの状態になるようにすることを意味する——気が散るものがすでに目の前に現れてから意志力で戦うのではなく。これは自己規律よりも信頼できる方法だ。なぜなら、判断そのものを不要にするからだ。すでにオフにした通知は、どれだけ疲れていても、どれだけやる気がなくても、あなたを誘惑することはできない。\n\nいくつかの変更でほとんどをカバーできる。個別に無視しようとするのではなく、重要でない通知はシステムレベルでオフにすること。集中する時間帯にはスマートフォンを机の上に伏せて置くのではなく、別の部屋に置くこと——視界に入るだけで、使える注意力が明確に減ることが分かっているからだ。そして、前の晩に作業スペースを整えておき、集中セッションの最初の十分間をファイル探しや何をすべきかの決定に費やさずに済むようにすること。これらの変更はどれも新しいソフトウェアや大掛かりなシステム改革を必要としない。必要なのは、少数の決定を一度だけ行い、毎日それを繰り返さずに済むようにすることだ。",
      "他者から集中時間を守ることは、たいてい最も難しい部分だ。断ることが人間関係を損なったり、チームプレイヤーではないという印象を与えたりするように感じられるからだ。解決策は、連絡が取りにくい人になることではなく、常に対応可能であるのではなく、予測可能なスケジュールで対応可能であることだ。そして、そのスケジュールを明確に伝えることで、周囲がそれに驚かされるのではなく、それを前提に計画を立てられるようにする。\n\nいくつかの言い回しが役立つ。「午後2時まで集中作業中です——その直後に対応してもいいですか？」は、際限のない断りではなく、具体的な時間を示す。「次回の打ち合わせの議題に入れましょう」は、中断を予定された会話に変える。本当に緊急な用件については、何が集中ブロックを中断するに値するほど緊急なのかをあらかじめ合意しておくこと。そうすれば、例外はまれなままであり、いつの間にかシステム全体を蝕むルールになることはない。",
      "習慣はフィードバックのループがなければ薄れていく。何も記録しなければ、良いスタートを切った最初の週も、平凡な二週目の中で簡単に失われてしまう。週次レビューはそのループを閉じる役割を果たす。週に一度、十分間かけて三つの質問に答える——実際に完了させた集中ブロックはいくつだったか、最も頻繁に自分を中断させたものは何だったか、来週に向けた一つの改善点は何か。\n\nこのレビューが機能するのは、集中を曖昧な意志から、測定可能な実践へと変えるからだ。体重や支出を記録するだけで行動が変わるのと同じ仕組みである。レビューは凝ったものにするのではなく、短くて一貫したものに保つこと——毎週続ける十分間の習慣は、一度だけ行って二度と繰り返さない徹底的な棚卸しに勝る。数か月経てば、この一つの習慣こそが、生産性ガイドを一度読んだだけの人と、実際に働き方を変えた人とを分けることになる。",
    ],
  },
  {
    languageCode: "fr",
    chapters: [
      "Pendant la majeure partie de l'histoire, la plupart des emplois ne récompensaient pas la concentration soutenue. La production dépendait des heures passées à un poste de travail, non de la qualité de la pensée pendant ces heures. Cette logique s'est discrètement inversée. Dans le travail intellectuel, deux personnes disposant des mêmes outils et du même temps peuvent produire des résultats radicalement différents, et la différence tient presque toujours à la capacité de garder un problème difficile en tête sans le laisser se fragmenter.\n\nCette capacité est aujourd'hui rare, et ce qui est rare a de la valeur. Le travailleur intellectuel moyen est interrompu toutes les quelques minutes par une notification, un message, ou sa propre habitude de vérifier quelque chose. Chacune de ces interruptions est minime prise isolément — c'est précisément ce qui les rend dangereuses, car aucune ne ressemble à une décision d'abandonner sa concentration, si bien que personne ne la choisit jamais consciemment. Considérer la concentration comme une compétence qui s'entraîne, plutôt qu'un trait que l'on possède ou non, est le premier changement que ce livre vous demande d'adopter.",
      "Changer de contexte donne une impression d'efficacité. Ce n'en est pas une. Chaque fois que vous passez d'une tâche à une autre — même une tâche mineure, comme jeter un œil à une notification de discussion — votre cerveau ne referme pas proprement la première tâche avant d'ouvrir la seconde. Une partie de votre attention reste en arrière, continuant à traiter ce que vous avez laissé inachevé, un phénomène que les chercheurs appellent le résidu d'attention. Résultat : la seconde tâche reçoit moins de vous que si vous aviez correctement terminé la première.\n\nLe coût s'accumule. Une seule interruption de quelques secondes peut coûter quinze à vingt-cinq minutes de véritable récupération de concentration, car vous ne reprenez pas simplement une tâche — vous reconstruisez le modèle mental que vous aviez bâti avant l'interruption. Multipliez cela par les dizaines de petites interruptions d'une journée ordinaire, et la plupart des gens ne sont jamais à plus de quelques minutes de travailler à capacité partielle. Prendre conscience de ce coût fait que protéger sa concentration ressemble moins à un luxe qu'à une simple question d'économie.",
      "La volonté est un moyen peu fiable d'entamer un travail en profondeur, car elle dépend d'un état mental déjà épuisé au moment précis où vous en avez le plus besoin. Un rituel fonctionne mieux : une courte séquence d'actions fixes, répétée à l'identique à chaque fois, jusqu'à ce que votre cerveau apprenne à associer cette séquence elle-même au basculement vers le travail concentré — de la même manière que l'échauffement d'un coureur signale au corps de se préparer, indépendamment de sa motivation ce jour-là.\n\nUn rituel en trois étapes qui fonctionne : d'abord, fermez tout ce qui n'a pas de rapport avec la tâche et écrivez en une phrase, en haut d'une page ou d'un document vierge, le seul résultat que vous visez. Ensuite, réglez une minuterie visible pour un créneau fixe — vingt-cinq à cinquante minutes constituent une plage de départ raisonnable. Enfin, prenez une respiration délibérée et commencez par la plus petite portion possible de la tâche, non par son intégralité. Les étapes précises comptent moins que la répétition ; c'est la constance qui transforme le rituel en déclencheur.",
      "Concevoir son environnement signifie modifier son cadre pour que la concentration devienne l'état par défaut, plutôt que quelque chose qu'il faut défendre par la volonté une fois la distraction déjà présente. Cette approche est plus fiable que l'autodiscipline, car elle supprime entièrement la décision : une notification déjà désactivée ne peut pas vous tenter, quel que soit votre niveau de fatigue ou de motivation.\n\nUne courte liste de changements couvre l'essentiel : désactivez les notifications non essentielles au niveau du système plutôt que d'essayer de les ignorer une à une ; laissez votre téléphone dans une autre pièce pendant les périodes de concentration plutôt que de le poser retourné sur le bureau, car sa simple visibilité réduit mesurablement l'attention disponible ; et préparez votre espace de travail la veille au soir, afin que les dix premières minutes d'une session de concentration ne soient pas consacrées à chercher des fichiers ou à décider quoi faire. Aucun de ces changements ne nécessite un nouveau logiciel ni une refonte complète du système — il suffit de prendre un petit nombre de décisions une seule fois, pour ne plus avoir à les reprendre chaque jour.",
      "Protéger son temps de concentration face aux autres est généralement la partie la plus difficile, car refuser peut donner l'impression d'abîmer une relation ou de signaler qu'on n'est pas un bon coéquipier. La solution n'est pas de devenir moins disponible, mais d'être disponible selon un horaire prévisible plutôt que constamment, et de communiquer cet horaire clairement afin que les autres puissent s'organiser en conséquence plutôt que d'être pris au dépourvu.\n\nQuelques formules aident : « Je suis concentré jusqu'à 14h — puis-je vous répondre juste après ? » offre un moment concret plutôt qu'un refus sans échéance. « Mettons cela à l'ordre du jour de notre prochaine réunion » transforme une interruption en conversation planifiée. Pour les urgences réelles, mettez-vous d'accord à l'avance sur ce qui justifie suffisamment d'interrompre un créneau de concentration, afin que l'exception reste rare au lieu de devenir la règle qui érode discrètement tout le système.",
      "Les habitudes s'estompent sans boucle de rétroaction, et une bonne première semaine de travail concentré se perd facilement dans une deuxième semaine médiocre si rien n'est suivi. Une revue hebdomadaire referme cette boucle : une fois par semaine, consacrez dix minutes à répondre à trois questions — combien de créneaux de concentration ai-je réellement accomplis, qu'est-ce qui m'a interrompu le plus souvent, et quel est un ajustement pour la semaine prochaine.\n\nCette revue fonctionne parce qu'elle transforme la concentration d'une intention vague en une pratique mesurée, tout comme suivre son poids ou ses dépenses modifie le comportement simplement en le rendant visible. Gardez la revue brève et régulière plutôt qu'élaborée et occasionnelle ; une habitude de dix minutes répétée chaque semaine l'emporte sur un bilan approfondi fait une fois et jamais renouvelé. Au bout de quelques mois, c'est généralement cette seule habitude qui distingue ceux qui ont simplement lu un guide de productivité de ceux qui ont réellement changé leur façon de travailler.",
    ],
  },
  {
    languageCode: "de",
    chapters: [
      "Über den größten Teil der Geschichte hinweg belohnten die meisten Berufe keine anhaltende Konzentration. Die Leistung war an die Stunden am Arbeitsplatz gebunden, nicht an die Qualität des Denkens während dieser Stunden. Das hat sich still und leise umgekehrt. In der Wissensarbeit können zwei Menschen mit denselben Werkzeugen und derselben Zeit völlig unterschiedliche Ergebnisse erzielen, und der Unterschied liegt fast immer in der Fähigkeit, ein einziges schwieriges Problem im Kopf zu behalten, ohne es zerfasern zu lassen.\n\nDiese Fähigkeit ist heute selten, und Seltenes ist wertvoll. Der durchschnittliche Wissensarbeiter wird alle paar Minuten durch eine Benachrichtigung, eine Nachricht oder die eigene Gewohnheit, etwas zu überprüfen, unterbrochen. Jede dieser Unterbrechungen ist für sich genommen klein — genau das macht sie gefährlich, denn keine fühlt sich wie eine bewusste Entscheidung an, den Fokus aufzugeben, weshalb niemand sie je bewusst trifft. Fokus als trainierbare Fähigkeit zu betrachten, statt als angeborene Eigenschaft, die man entweder hat oder nicht, ist die erste Umstellung, die dieses Buch von dir verlangt.",
      "Aufgabenwechsel fühlt sich effizient an. Ist er aber nicht. Jedes Mal, wenn du von einer Aufgabe zur nächsten wechselst — selbst bei etwas Kleinem wie einem kurzen Blick auf eine Chat-Benachrichtigung —, schließt dein Gehirn die erste Aufgabe nicht sauber ab, bevor es die zweite öffnet. Ein Teil deiner Aufmerksamkeit bleibt zurück und verarbeitet weiterhin das Unerledigte — ein Phänomen, das Forscher als Aufmerksamkeitsrückstand bezeichnen. Das Ergebnis: Die zweite Aufgabe bekommt weniger von dir, als wenn du die erste ordentlich beendet hättest.\n\nDie Kosten summieren sich. Eine einzige Unterbrechung von wenigen Sekunden kann fünfzehn bis fünfundzwanzig Minuten echter Fokus-Erholungszeit kosten, denn du nimmst nicht einfach eine Aufgabe wieder auf — du rekonstruierst das mentale Modell, das du vor der Unterbrechung aufgebaut hattest. Multipliziere das mit den Dutzenden kleinen Unterbrechungen eines durchschnittlichen Tages, und die meisten Menschen arbeiten fast nie mehr als ein paar Minuten am Stück mit voller Kapazität. Diese Kosten zu erkennen, macht den Schutz des Fokus weniger zu einem Luxus als zu einer schlichten wirtschaftlichen Rechnung.",
      "Willenskraft ist ein unzuverlässiger Weg, um konzentriertes Arbeiten zu beginnen, da sie von einem mentalen Zustand abhängt, der genau dann bereits erschöpft ist, wenn du sie am meisten brauchst. Ein Ritual funktioniert besser: eine kurze, feste Abfolge von Handlungen, die du jedes Mal identisch wiederholst, bis dein Gehirn lernt, diese Abfolge selbst mit dem Übergang in konzentriertes Arbeiten zu verknüpfen — so wie das Aufwärmen eines Läufers dem Körper signalisiert, sich vorzubereiten, unabhängig davon, wie motiviert der Läufer an diesem Tag ist.\n\nEin funktionierendes Drei-Schritte-Ritual: Schließe zuerst alles, was nichts mit der Aufgabe zu tun hat, und schreibe das eine Ergebnis, das du anstrebst, in einem Satz oben auf ein leeres Blatt oder Dokument. Stelle zweitens einen sichtbaren Timer für einen festen Zeitblock — fünfundzwanzig bis fünfzig Minuten sind ein vernünftiger Startbereich. Atme drittens bewusst einmal ein und beginne mit dem kleinstmöglichen Teil der Aufgabe, nicht mit dem Ganzen. Die konkreten Schritte zählen weniger als die Wiederholung; Beständigkeit ist es, die das Ritual zu einem Auslöser macht.",
      "Umgebungsgestaltung bedeutet, dein Umfeld so zu verändern, dass Fokus zum Normalzustand wird, statt etwas, das du erst mit Willenskraft erkämpfen musst, nachdem die Ablenkung bereits vor dir liegt. Das ist zuverlässiger als Selbstdisziplin, weil es die Entscheidung komplett überflüssig macht — eine bereits stummgeschaltete Benachrichtigung kann dich nicht verführen, egal wie müde oder unmotiviert du bist.\n\nEine kurze Liste von Änderungen deckt das Wesentliche ab: Schalte nicht essenzielle Benachrichtigungen auf Systemebene aus, statt zu versuchen, sie einzeln zu ignorieren; lass dein Handy während der Fokusblöcke in einem anderen Raum, statt es nur umgedreht auf den Schreibtisch zu legen, denn allein die Sichtbarkeit verringert nachweislich die verfügbare Aufmerksamkeit; und bereite deinen Arbeitsplatz am Vorabend vor, damit die ersten zehn Minuten einer Fokussitzung nicht mit der Suche nach Dateien oder der Entscheidung verstreichen, woran du arbeiten sollst. Keine dieser Änderungen erfordert neue Software oder eine komplette Systemumstellung — es braucht nur eine kleine Zahl von Entscheidungen, die du einmal triffst, statt sie täglich neu treffen zu müssen.",
      "Die Fokuszeit vor anderen Menschen zu schützen, ist meist der schwierigste Teil, denn Nein zu sagen kann sich anfühlen, als würde es eine Beziehung beschädigen oder signalisieren, dass man kein Teamplayer ist. Die Lösung besteht nicht darin, weniger erreichbar zu sein — sondern nach einem vorhersehbaren Zeitplan erreichbar zu sein statt ständig, und diesen Zeitplan klar zu kommunizieren, damit andere sich darauf einstellen können, statt davon überrascht zu werden.\n\nEinige Formulierungen helfen: „Ich bin bis 14 Uhr konzentriert bei der Sache — kann ich mich direkt danach melden?“ gibt einen konkreten Zeitpunkt statt eines offenen Neins. „Lass uns das auf die Agenda unseres nächsten Meetings setzen“ verwandelt eine Unterbrechung in ein geplantes Gespräch. Für wirklich dringende Angelegenheiten sollte im Voraus vereinbart werden, was dringend genug ist, um einen Fokusblock zu unterbrechen, damit die Ausnahme selten bleibt, statt sich still und leise zur Regel zu entwickeln, die das ganze System untergräbt.",
      "Gewohnheiten verblassen ohne Rückkopplung, und eine gute erste Woche konzentrierten Arbeitens geht in einer mittelmäßigen zweiten Woche leicht verloren, wenn nichts erfasst wird. Ein wöchentlicher Rückblick schließt diese Lücke: Nimm dir einmal pro Woche zehn Minuten Zeit, um drei Fragen zu beantworten — wie viele Fokusblöcke habe ich tatsächlich abgeschlossen, was hat mich am häufigsten unterbrochen, und was ist eine Anpassung für nächste Woche.\n\nDer Rückblick funktioniert, weil er Fokus von einer vagen Absicht in eine gemessene Praxis verwandelt — genau wie das Erfassen von Gewicht oder Ausgaben das Verhalten allein dadurch verändert, dass es sichtbar wird. Halte den Rückblick kurz und regelmäßig statt aufwendig und gelegentlich; eine zehnminütige Gewohnheit, die du jede Woche durchführst, schlägt eine gründliche Bestandsaufnahme, die du einmal machst und nie wiederholst. Nach ein paar Monaten ist es meist genau diese eine Gewohnheit, die Menschen, die einen Produktivitätsratgeber einmal gelesen haben, von denen unterscheidet, die ihre Arbeitsweise tatsächlich verändert haben.",
    ],
  },
  {
    languageCode: "ar",
    chapters: [
      "على مدى معظم التاريخ، لم تكن أغلب الوظائف تكافئ التركيز المستمر. كان الإنتاج مرتبطًا بعدد الساعات التي تُقضى خلف مكتب، لا بجودة التفكير خلال تلك الساعات. وقد انعكس هذا الوضع بهدوء. ففي العمل المعرفي، يمكن لشخصين يمتلكان نفس الأدوات ونفس الوقت أن ينتجا نتائج مختلفة تمامًا، ويكاد الفرق يكون دائمًا في القدرة على الاحتفاظ بمشكلة صعبة واحدة في الذهن دون أن تتشتت.\n\nهذه القدرة أصبحت اليوم نادرة، والنادر ثمين. يتعرض العامل المعرفي العادي للمقاطعة كل بضع دقائق بسبب إشعار، أو رسالة، أو عادته الخاصة في تفقّد شيء ما. كل مقاطعة من هذه المقاطعات صغيرة بمفردها — وهذا بالضبط ما يجعلها خطيرة، إذ لا تبدو أي واحدة منها وكأنها قرار بالتخلي عن التركيز، فلا يختارها أحد بوعي أبدًا. التعامل مع التركيز باعتباره مهارة يمكن تدريبها، لا سمة تولد بها أو بدونها، هو التحول الأول الذي يطلبه منك هذا الكتاب.",
      "يبدو تبديل السياق وكأنه أمر فعّال. لكنه ليس كذلك. في كل مرة تنتقل فيها من مهمة إلى أخرى — حتى لو كانت صغيرة، مثل إلقاء نظرة على إشعار محادثة — لا يغلق دماغك المهمة الأولى بشكل نظيف قبل فتح الثانية. يبقى جزء من انتباهك في الخلف، لا يزال يعالج ما تركته غير مكتمل، في ظاهرة يسميها الباحثون بقايا الانتباه. والنتيجة أن المهمة الثانية تحصل منك على أقل مما كانت ستحصل عليه لو أنهيت الأولى بشكل صحيح.\n\nوتتراكم التكلفة. يمكن لمقاطعة واحدة لا تتجاوز بضع ثوانٍ أن تكلفك خمس عشرة إلى خمس وعشرين دقيقة من استعادة التركيز الحقيقي، لأنك لا تستأنف المهمة فحسب — بل تعيد بناء النموذج الذهني الذي كنت قد بنيته قبل المقاطعة. اضرب ذلك في عشرات المقاطعات الصغيرة في اليوم العادي، وستجد أن معظم الناس لا يبتعدون أبدًا أكثر من بضع دقائق عن العمل بقدرة جزئية. إدراك هذه التكلفة هو ما يجعل حماية التركيز تبدو أقل ترفًا وأقرب إلى حساب اقتصادي بسيط.",
      "قوة الإرادة وسيلة غير موثوقة لبدء العمل العميق، لأنها تعتمد على حالة ذهنية تكون قد استُنزفت بالفعل في اللحظة التي تحتاجها فيها أكثر ما تحتاج. الطقوس (الروتين الثابت) تعمل بشكل أفضل: سلسلة قصيرة وثابتة من الأفعال تكررها بنفس الطريقة في كل مرة، حتى يتعلم دماغك ربط السلسلة نفسها بالانتقال إلى العمل المركّز — تمامًا كما يرسل إحماء العدّاء إشارة لجسده بالاستعداد، بغض النظر عن مدى حماسه في ذلك اليوم.\n\nطقس عملي من ثلاث خطوات: أولًا، أغلق كل ما لا علاقة له بالمهمة، واكتب النتيجة الوحيدة التي تسعى إليها في جملة واحدة في أعلى صفحة أو مستند فارغ. ثانيًا، اضبط مؤقتًا مرئيًا لفترة زمنية ثابتة — تُعد خمس وعشرون إلى خمسون دقيقة نطاقًا معقولًا للبداية. ثالثًا، خذ نفسًا واحدًا بوعي، وابدأ بأصغر جزء ممكن من المهمة، لا بالمهمة كاملة. الخطوات المحددة أقل أهمية من التكرار نفسه؛ فالاتساق هو ما يحوّل الطقس إلى محفّز.",
      "تصميم البيئة يعني تغيير محيطك بحيث يصبح التركيز هو الحالة الافتراضية، بدلًا من أن يكون شيئًا عليك أن تحاربه بقوة الإرادة بعد أن يكون التشتيت قد أصبح بالفعل أمامك. وهذا أكثر موثوقية من الانضباط الذاتي لأنه يلغي القرار تمامًا — فالإشعار الذي أسكتّه مسبقًا لا يمكنه إغراؤك، مهما كنت متعبًا أو غير متحمس.\n\nقائمة قصيرة من التغييرات تغطي معظم الأساس: أطفئ الإشعارات غير الضرورية على مستوى النظام بدلًا من محاولة تجاهلها واحدة تلو الأخرى؛ اترك هاتفك في غرفة أخرى أثناء فترات التركيز بدلًا من مجرد قلبه على المكتب، لأن مجرد رؤيته يقلل بشكل ملموس من الانتباه المتاح؛ وجهّز مساحة عملك في الليلة السابقة، حتى لا تُهدر الدقائق العشر الأولى من جلسة التركيز في البحث عن الملفات أو تحديد ما ستعمل عليه. لا يتطلب أي من هذه التغييرات برنامجًا جديدًا أو إعادة هيكلة كاملة للنظام — بل يتطلب اتخاذ عدد قليل من القرارات مرة واحدة، حتى لا تضطر إلى اتخاذها كل يوم.",
      "حماية وقت التركيز من الآخرين عادة ما تكون الجزء الأصعب، لأن الرفض قد يبدو وكأنه يضر بعلاقة ما أو يوحي بأنك لست لاعب فريق. الحل ليس أن تصبح أقل توفرًا — بل أن تكون متاحًا وفق جدول يمكن التنبؤ به بدلًا من التواجد الدائم، وأن توصل هذا الجدول بوضوح حتى يتمكن الآخرون من التخطيط حوله بدلًا من أن يُفاجَأوا به.\n\nبعض العبارات المفيدة: \"أنا منشغل بالتركيز حتى الساعة الثانية ظهرًا — هل يمكنني الرد عليك مباشرة بعد ذلك؟\" تمنح وقتًا محددًا بدلًا من رفض مفتوح. \"لنضع هذا على جدول أعمال اجتماعنا القادم\" تحوّل المقاطعة إلى محادثة مجدولة. أما بالنسبة للأمور العاجلة حقًا، فاتفق مسبقًا على ما يُعتبر عاجلًا بما يكفي لمقاطعة فترة التركيز، بحيث يبقى الاستثناء نادرًا بدلًا من أن يتحول بهدوء إلى قاعدة تآكل النظام بأكمله.",
      "تتلاشى العادات دون حلقة تغذية راجعة، ويسهل أن يضيع أسبوع أول جيد من العمل المركّز في أسبوع ثانٍ عادي إذا لم يُتابَع شيء. تُغلق المراجعة الأسبوعية هذه الحلقة: مرة كل أسبوع، خصص عشر دقائق للإجابة عن ثلاثة أسئلة — كم عدد فترات التركيز التي أنجزتها فعليًا، وما الذي قاطعني أكثر من غيره، وما التعديل الذي سأجريه للأسبوع القادم.\n\nتنجح هذه المراجعة لأنها تحوّل التركيز من نية غامضة إلى ممارسة قابلة للقياس، تمامًا كما يغيّر تتبع الوزن أو الإنفاق السلوك لمجرد جعله مرئيًا. اجعل المراجعة قصيرة ومنتظمة بدلًا من مفصّلة وعرضية؛ فعادة مدتها عشر دقائق تكررها كل أسبوع أفضل من مراجعة شاملة تجريها مرة واحدة ولا تكررها أبدًا. بعد بضعة أشهر، عادة ما تكون هذه العادة الوحيدة هي ما يفرّق بين من قرأ دليل إنتاجية مرة واحدة، ومن غيّر فعليًا طريقة عمله.",
    ],
  },
];
